/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StaffManagement.UserInterface;
import StaffManagement.BusinessLogic.LoginController;
import StaffManagement.BusinessLogic.ResetPasswordController;
import javax.swing.JOptionPane;
/**
 *
 * @author ssarkar
 */
public class LoginUI extends javax.swing.JFrame {

    private int xx;
    private int xy;
    private boolean maximized = true;
    
    /**
     * Creates new form LoginUI
     */
    public LoginUI() {
        initComponents();
        this.showLogin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_pnl = new javax.swing.JPanel();
        user_login_heading_lbl = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        user_icon_lbl = new javax.swing.JLabel();
        emp_mgmt_login_lbl = new javax.swing.JLabel();
        exit_pnl = new javax.swing.JPanel();
        exit_lbl = new javax.swing.JLabel();
        login_form_pnl = new javax.swing.JPanel();
        l_username_input = new javax.swing.JTextField();
        l_username_lbl = new javax.swing.JLabel();
        l_password_lbl = new javax.swing.JLabel();
        l_password_input = new javax.swing.JPasswordField();
        l_forgot_password_lbl = new javax.swing.JLabel();
        l_error_lbl = new javax.swing.JLabel();
        login_btn_pnl = new javax.swing.JPanel();
        login_btn_lbl = new javax.swing.JLabel();
        reset_password_form_pnl = new javax.swing.JPanel();
        rp_username_input = new javax.swing.JTextField();
        rp_username_lbl = new javax.swing.JLabel();
        rp_new_password_lbl = new javax.swing.JLabel();
        rp_new_password_input = new javax.swing.JPasswordField();
        rp_confirm_password_lbl = new javax.swing.JLabel();
        chng_password_btn_pnl = new javax.swing.JPanel();
        change_password_btn_lbl = new javax.swing.JLabel();
        rp_confirm_password_input = new javax.swing.JPasswordField();
        rp_email_lbl = new javax.swing.JLabel();
        rp_email_input = new javax.swing.JTextField();
        rp_error_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        login_pnl.setBackground(new java.awt.Color(255, 255, 255));
        login_pnl.setLayout(null);

        user_login_heading_lbl.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        user_login_heading_lbl.setForeground(new java.awt.Color(102, 102, 102));
        user_login_heading_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_login_heading_lbl.setText("Staff Management");
        login_pnl.add(user_login_heading_lbl);
        user_login_heading_lbl.setBounds(325, 50, 650, 40);

        back.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StaffManagement/UserInterface/Images/back.png"))); // NOI18N
        back.setToolTipText("Return to Log In Screen");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        login_pnl.add(back);
        back.setBounds(0, 0, 60, 60);

        sidebar.setBackground(new java.awt.Color(0, 102, 204));
        sidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sidebarMouseDragged(evt);
            }
        });
        sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidebarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sidebarMouseReleased(evt);
            }
        });

        user_icon_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_icon_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StaffManagement/UserInterface/Images/user.png"))); // NOI18N

        emp_mgmt_login_lbl.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        emp_mgmt_login_lbl.setForeground(new java.awt.Color(255, 255, 255));
        emp_mgmt_login_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emp_mgmt_login_lbl.setText("Login");

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emp_mgmt_login_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(user_icon_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(user_icon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emp_mgmt_login_lbl)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        login_pnl.add(sidebar);
        sidebar.setBounds(0, 0, 260, 0);

        exit_pnl.setBackground(new java.awt.Color(0, 102, 204));
        exit_pnl.setPreferredSize(new java.awt.Dimension(40, 40));

        exit_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        exit_lbl.setForeground(new java.awt.Color(255, 255, 255));
        exit_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StaffManagement/UserInterface/Images/close.png"))); // NOI18N
        exit_lbl.setToolTipText("Exit");
        exit_lbl.setAlignmentY(0.0F);
        exit_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exit_lbl.setPreferredSize(new java.awt.Dimension(40, 40));
        exit_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_lblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout exit_pnlLayout = new javax.swing.GroupLayout(exit_pnl);
        exit_pnl.setLayout(exit_pnlLayout);
        exit_pnlLayout.setHorizontalGroup(
            exit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exit_pnlLayout.createSequentialGroup()
                .addComponent(exit_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        exit_pnlLayout.setVerticalGroup(
            exit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exit_pnlLayout.createSequentialGroup()
                .addComponent(exit_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        login_pnl.add(exit_pnl);
        exit_pnl.setBounds(1002, 0, 40, 40);

        login_form_pnl.setBackground(new java.awt.Color(255, 255, 255));
        login_form_pnl.setMinimumSize(new java.awt.Dimension(740, 566));
        login_form_pnl.setPreferredSize(new java.awt.Dimension(740, 566));
        login_form_pnl.setLayout(null);

        l_username_input.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        l_username_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        l_username_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_username_inputActionPerformed(evt);
            }
        });
        login_form_pnl.add(l_username_input);
        l_username_input.setBounds(65, 180, 650, 40);

        l_username_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        l_username_lbl.setText("Username");
        login_form_pnl.add(l_username_lbl);
        l_username_lbl.setBounds(65, 150, 650, 30);

        l_password_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        l_password_lbl.setText("Password");
        login_form_pnl.add(l_password_lbl);
        l_password_lbl.setBounds(65, 250, 650, 30);

        l_password_input.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        l_password_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        login_form_pnl.add(l_password_input);
        l_password_input.setBounds(65, 280, 650, 40);

        l_forgot_password_lbl.setBackground(new java.awt.Color(240, 240, 240));
        l_forgot_password_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        l_forgot_password_lbl.setForeground(new java.awt.Color(0, 102, 204));
        l_forgot_password_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_forgot_password_lbl.setText("Forgot Password?");
        l_forgot_password_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l_forgot_password_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_forgot_password_lblMouseClicked(evt);
            }
        });
        login_form_pnl.add(l_forgot_password_lbl);
        l_forgot_password_lbl.setBounds(65, 433, 650, 30);

        l_error_lbl.setBackground(new java.awt.Color(240, 240, 240));
        l_error_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        l_error_lbl.setForeground(new java.awt.Color(204, 0, 0));
        l_error_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_error_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_form_pnl.add(l_error_lbl);
        l_error_lbl.setBounds(65, 503, 650, 30);

        login_btn_pnl.setBackground(new java.awt.Color(0, 102, 204));
        login_btn_pnl.setForeground(new java.awt.Color(255, 255, 255));
        login_btn_pnl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        login_btn_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        login_btn_lbl.setForeground(new java.awt.Color(255, 255, 255));
        login_btn_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_btn_lbl.setText("Login");
        login_btn_lbl.setAlignmentY(0.0F);
        login_btn_lbl.setFocusCycleRoot(true);
        login_btn_lbl.setName("login_btn"); // NOI18N
        login_btn_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btn_lblMouseClicked(evt);
            }
        });
        login_btn_lbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                login_btn_lblKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout login_btn_pnlLayout = new javax.swing.GroupLayout(login_btn_pnl);
        login_btn_pnl.setLayout(login_btn_pnlLayout);
        login_btn_pnlLayout.setHorizontalGroup(
            login_btn_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_btn_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        login_btn_pnlLayout.setVerticalGroup(
            login_btn_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_btn_pnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login_btn_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        login_form_pnl.add(login_btn_pnl);
        login_btn_pnl.setBounds(220, 363, 0, 0);

        login_pnl.add(login_form_pnl);
        login_form_pnl.setBounds(260, 0, 780, 566);

        reset_password_form_pnl.setBackground(new java.awt.Color(255, 255, 255));
        reset_password_form_pnl.setMinimumSize(new java.awt.Dimension(780, 566));
        reset_password_form_pnl.setLayout(null);

        rp_username_input.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        rp_username_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        rp_username_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp_username_inputActionPerformed(evt);
            }
        });
        reset_password_form_pnl.add(rp_username_input);
        rp_username_input.setBounds(50, 110, 650, 40);

        rp_username_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        rp_username_lbl.setText("Username");
        reset_password_form_pnl.add(rp_username_lbl);
        rp_username_lbl.setBounds(50, 80, 650, 30);

        rp_new_password_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        rp_new_password_lbl.setText("New Password");
        reset_password_form_pnl.add(rp_new_password_lbl);
        rp_new_password_lbl.setBounds(50, 260, 650, 30);

        rp_new_password_input.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        rp_new_password_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        reset_password_form_pnl.add(rp_new_password_input);
        rp_new_password_input.setBounds(50, 290, 650, 40);

        rp_confirm_password_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        rp_confirm_password_lbl.setText("Confirm Password");
        reset_password_form_pnl.add(rp_confirm_password_lbl);
        rp_confirm_password_lbl.setBounds(50, 350, 650, 30);

        chng_password_btn_pnl.setBackground(new java.awt.Color(0, 102, 204));
        chng_password_btn_pnl.setForeground(new java.awt.Color(255, 255, 255));
        chng_password_btn_pnl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        change_password_btn_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        change_password_btn_lbl.setForeground(new java.awt.Color(255, 255, 255));
        change_password_btn_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        change_password_btn_lbl.setText("Change Password");
        change_password_btn_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                change_password_btn_lblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout chng_password_btn_pnlLayout = new javax.swing.GroupLayout(chng_password_btn_pnl);
        chng_password_btn_pnl.setLayout(chng_password_btn_pnlLayout);
        chng_password_btn_pnlLayout.setHorizontalGroup(
            chng_password_btn_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chng_password_btn_pnlLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(change_password_btn_lbl)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        chng_password_btn_pnlLayout.setVerticalGroup(
            chng_password_btn_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(change_password_btn_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        reset_password_form_pnl.add(chng_password_btn_pnl);
        chng_password_btn_pnl.setBounds(210, 450, 340, 50);

        rp_confirm_password_input.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        rp_confirm_password_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        reset_password_form_pnl.add(rp_confirm_password_input);
        rp_confirm_password_input.setBounds(50, 380, 650, 40);

        rp_email_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        rp_email_lbl.setText("Email ID");
        reset_password_form_pnl.add(rp_email_lbl);
        rp_email_lbl.setBounds(50, 170, 650, 30);

        rp_email_input.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        rp_email_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        rp_email_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp_email_inputActionPerformed(evt);
            }
        });
        reset_password_form_pnl.add(rp_email_input);
        rp_email_input.setBounds(50, 200, 650, 40);

        rp_error_lbl.setBackground(new java.awt.Color(240, 240, 240));
        rp_error_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        rp_error_lbl.setForeground(new java.awt.Color(204, 0, 0));
        rp_error_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rp_error_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset_password_form_pnl.add(rp_error_lbl);
        rp_error_lbl.setBounds(50, 510, 650, 30);

        login_pnl.add(reset_password_form_pnl);
        reset_password_form_pnl.setBounds(260, 0, 780, 566);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_sidebarMouseDragged

    private void sidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebarMousePressed
        setOpacity((float)0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_sidebarMousePressed

    private void sidebarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebarMouseReleased
        setOpacity((float)1.0);
    }//GEN-LAST:event_sidebarMouseReleased

    private void exit_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_lblMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exit_lblMouseClicked

    private void l_username_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_username_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_username_inputActionPerformed

    private void l_forgot_password_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_forgot_password_lblMouseClicked
        this.login_form_pnl.setVisible(false);
        this.reset_password_form_pnl.setVisible(true);
        this.emp_mgmt_login_lbl.setText("Reset Password");
        this.back.setVisible(true);
        
    }//GEN-LAST:event_l_forgot_password_lblMouseClicked

    private void login_btn_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btn_lblMouseClicked
        boolean attempt_login;
        String username = l_username_input.getText();
        String password = String.valueOf(l_password_input.getPassword());
        if ( username.isEmpty() || password.isEmpty()) {
            l_error_lbl.setText("Please fill up all fields");
        }
        else {
            attempt_login = LoginController.attempt_login(username, password);
            if (attempt_login) {
                l_error_lbl.setText("");
                this.dispose();
                new ManagerUI().setVisible(true);
            } else {
                l_error_lbl.setText("Incorrect Login Credentials!");
            }
        }
    }//GEN-LAST:event_login_btn_lblMouseClicked

    private void login_btn_lblKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_btn_lblKeyReleased
        //this.attempt_login();
    }//GEN-LAST:event_login_btn_lblKeyReleased

    private void rp_username_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp_username_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rp_username_inputActionPerformed

    private void change_password_btn_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_change_password_btn_lblMouseClicked
        String username = rp_username_input.getText();
        String email = rp_email_input.getText();
        String new_password = String.valueOf(rp_new_password_input.getPassword());
        String confirm_password = String.valueOf(rp_confirm_password_input.getPassword());
        
        if (new_password.isEmpty() || confirm_password.isEmpty() || email.isEmpty() || username.isEmpty()) {
            rp_error_lbl.setText("Please fill up all fields");
        }
        else {
            if (new_password.equals(confirm_password)) {
                rp_error_lbl.setText("");
                int attempt_password_reset = ResetPasswordController.attempt_password_reset(username, email, new_password, confirm_password);
                if (attempt_password_reset < 1) {
                    rp_error_lbl.setText("");
                    JOptionPane.showMessageDialog(null, "Password Updated!");
                    this.showLogin();
                } else {
                    if(attempt_password_reset == 1) {
                        rp_error_lbl.setText("There was an error updating the password.");
                    } else if(attempt_password_reset == 2) {
                        rp_error_lbl.setText("This Email ID does not belong to this Username in our records.");
                    }
                }
            } else {
                rp_error_lbl.setText("Both passwords do not match.");
            }
        }
    }//GEN-LAST:event_change_password_btn_lblMouseClicked

    private void rp_email_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp_email_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rp_email_inputActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        this.showLogin();
    }//GEN-LAST:event_backMouseClicked

    private void showLogin() {
        this.reset_password_form_pnl.setVisible(false);
        this.login_form_pnl.setVisible(true);
        this.back.setVisible(false);
        this.emp_mgmt_login_lbl.setText("Login");
        l_error_lbl.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel change_password_btn_lbl;
    private javax.swing.JPanel chng_password_btn_pnl;
    private javax.swing.JLabel emp_mgmt_login_lbl;
    private javax.swing.JLabel exit_lbl;
    private javax.swing.JPanel exit_pnl;
    private javax.swing.JLabel l_error_lbl;
    private javax.swing.JLabel l_forgot_password_lbl;
    private javax.swing.JPasswordField l_password_input;
    private javax.swing.JLabel l_password_lbl;
    private javax.swing.JTextField l_username_input;
    private javax.swing.JLabel l_username_lbl;
    private javax.swing.JLabel login_btn_lbl;
    private javax.swing.JPanel login_btn_pnl;
    private javax.swing.JPanel login_form_pnl;
    private javax.swing.JPanel login_pnl;
    private javax.swing.JPanel reset_password_form_pnl;
    private javax.swing.JPasswordField rp_confirm_password_input;
    private javax.swing.JLabel rp_confirm_password_lbl;
    private javax.swing.JTextField rp_email_input;
    private javax.swing.JLabel rp_email_lbl;
    private javax.swing.JLabel rp_error_lbl;
    private javax.swing.JPasswordField rp_new_password_input;
    private javax.swing.JLabel rp_new_password_lbl;
    private javax.swing.JTextField rp_username_input;
    private javax.swing.JLabel rp_username_lbl;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel user_icon_lbl;
    private javax.swing.JLabel user_login_heading_lbl;
    // End of variables declaration//GEN-END:variables
}
