/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StaffManagement.UserInterface;

import StaffManagement.BusinessLogic.EmployeeManagement.AddEmployeeController;
import StaffManagement.BusinessLogic.EmployeeManagement.DeleteEmployeeController;
import StaffManagement.BusinessLogic.EmployeeManagement.ListEmployeesController;
import StaffManagement.BusinessLogic.EmployeeManagement.UpdateEmployeeController;
import StaffManagement.DataPersistence.EmployeeRepoImpl;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ssarkar
 */
public class ManagerUI extends javax.swing.JFrame {

    AddEmployeeController con = new AddEmployeeController();
    ListEmployeesController output = new ListEmployeesController();
    ArrayList list = new ArrayList();
    EmployeeRepoImpl empRepo = new EmployeeRepoImpl();
    Connection conn;
    private int xx;
    private int xy;
    /**
     * Creates new form ManagerUI
     */
    public ManagerUI() {
        initComponents();
        DefaultTableModel etm = (DefaultTableModel)employee_list_tbl.getModel();
        ListEmployeesController.listEmployees(etm);
        if (emp_type_full_rdo_btn.isSelected()) {
            emp_rate_lbl.setVisible(false);
            emp_rate_input.setVisible(false);
            emp_hours_lbl.setVisible(false);
            emp_hours_input.setVisible(false);
            emp_salary_lbl.setVisible(true);
            emp_salary_input.setVisible(true);
        } else {
            emp_rate_lbl.setVisible(true);
            emp_rate_input.setVisible(true);
            emp_hours_lbl.setVisible(true);
            emp_hours_input.setVisible(true);
            emp_salary_lbl.setVisible(false);
            emp_salary_input.setVisible(false);
        }
    }
    
    public ManagerUI(AddEmployeeController control, ListEmployeesController list, Connection connection) {
        initComponents();
        con = control;
        conn = connection;
        output = list;
    }
    
    private void setLblColor(JLabel lbl) {
        lbl.setBackground(new Color(0,51,153));
    }

    private void resetLblColor(JLabel lbl) {
        lbl.setBackground(new Color(0,102,204));
    }
    
    static public class TblHeaderColor extends DefaultTableCellRenderer {
        public TblHeaderColor() {
            setOpaque(true);
        }
        @Override
        public Component getTableCellRendererComponent(JTable mytable, Object value, boolean selected, boolean focusses, int row, int column) {
            super.getTableCellRendererComponent(mytable, value, selected, selected, row, column);
            setBackground(new Color(0,102,204));
            setForeground(Color.WHITE);
            setFont(new java.awt.Font("Calibri", 0, 18));
            setPreferredSize(new Dimension(110,32));
            return this;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emp_type_btn_grp = new javax.swing.ButtonGroup();
        home_pnl = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        user_login_heading_lbl = new javax.swing.JLabel();
        exit_pnl = new javax.swing.JPanel();
        exit_lbl = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        sidebar_menu = new javax.swing.JPanel();
        sidebar_invoice_lbl = new javax.swing.JLabel();
        sidebar_emp_list_btn_lbl = new javax.swing.JLabel();
        sidebar_add_emp_btn_lbl = new javax.swing.JLabel();
        sidebar_update_emp_btn_lbl = new javax.swing.JLabel();
        sidebar_delete_emp_btn_lbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        content = new javax.swing.JPanel();
        employee_list_scrl_pane = new javax.swing.JScrollPane();
        employee_list_tbl = new javax.swing.JTable();
        employee_form_pnl = new javax.swing.JPanel();
        emp_form_lbl = new javax.swing.JLabel();
        emp_id_input = new javax.swing.JTextField();
        emp_id_lbl = new javax.swing.JLabel();
        emp_address_lbl = new javax.swing.JLabel();
        emp_address_input = new javax.swing.JTextField();
        emp_rate_lbl = new javax.swing.JLabel();
        emp_rate_input = new javax.swing.JTextField();
        emp_hours_lbl = new javax.swing.JLabel();
        emp_hours_input = new javax.swing.JTextField();
        save_employee_btn_lbl = new javax.swing.JLabel();
        emp_type_full_rdo_btn = new javax.swing.JRadioButton();
        emp_type_part_rdo_btn = new javax.swing.JRadioButton();
        emp_type_lbl = new javax.swing.JLabel();
        emp_email_lbl = new javax.swing.JLabel();
        emp_email_input = new javax.swing.JTextField();
        emp_doj_date_input = new com.toedter.calendar.JDateChooser();
        emp_doj_date_lbl = new javax.swing.JLabel();
        emp_salary_input = new javax.swing.JTextField();
        emp_salary_lbl = new javax.swing.JLabel();
        emp_name_input = new javax.swing.JTextField();
        emp_name_lbl = new javax.swing.JLabel();
        update_employee_btn_lbl = new javax.swing.JLabel();
        delete_employee_pnl = new javax.swing.JPanel();
        delete_employee_lbl = new javax.swing.JLabel();
        delete_employee_id_input = new javax.swing.JTextField();
        delete_employee_id_lbl = new javax.swing.JLabel();
        delete_employee_btn_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        home_pnl.setBackground(new java.awt.Color(255, 255, 255));
        home_pnl.setLayout(null);

        header.setOpaque(false);
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                headerMouseReleased(evt);
            }
        });

        logout.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StaffManagement/UserInterface/Images/logout.png"))); // NOI18N
        logout.setToolTipText("Log Out");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        user_login_heading_lbl.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        user_login_heading_lbl.setForeground(new java.awt.Color(102, 102, 102));
        user_login_heading_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_login_heading_lbl.setText("Staff Management");
        user_login_heading_lbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        exit_pnl.setBackground(new java.awt.Color(0, 102, 204));
        exit_pnl.setAlignmentX(0.0F);
        exit_pnl.setAlignmentY(0.0F);
        exit_pnl.setPreferredSize(new java.awt.Dimension(40, 40));

        exit_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        exit_lbl.setForeground(new java.awt.Color(255, 255, 255));
        exit_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StaffManagement/UserInterface/Images/close.png"))); // NOI18N
        exit_lbl.setToolTipText("Exit");
        exit_lbl.setAlignmentY(0.0F);
        exit_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exit_lbl.setPreferredSize(new java.awt.Dimension(40, 40));
        exit_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_lblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout exit_pnlLayout = new javax.swing.GroupLayout(exit_pnl);
        exit_pnl.setLayout(exit_pnlLayout);
        exit_pnlLayout.setHorizontalGroup(
            exit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exit_pnlLayout.createSequentialGroup()
                .addComponent(exit_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        exit_pnlLayout.setVerticalGroup(
            exit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exit_pnlLayout.createSequentialGroup()
                .addComponent(exit_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                .addComponent(user_login_heading_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(exit_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exit_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(user_login_heading_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        home_pnl.add(header);
        header.setBounds(0, 0, 1042, 64);

        sidebar.setBackground(new java.awt.Color(0, 102, 204));

        sidebar_menu.setOpaque(false);

        sidebar_invoice_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        sidebar_invoice_lbl.setForeground(new java.awt.Color(255, 255, 255));
        sidebar_invoice_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sidebar_invoice_lbl.setText("MENU");

        sidebar_emp_list_btn_lbl.setBackground(new java.awt.Color(0, 51, 153));
        sidebar_emp_list_btn_lbl.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        sidebar_emp_list_btn_lbl.setForeground(new java.awt.Color(255, 255, 255));
        sidebar_emp_list_btn_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sidebar_emp_list_btn_lbl.setText("Employee List");
        sidebar_emp_list_btn_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sidebar_emp_list_btn_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidebar_emp_list_btn_lbl.setOpaque(true);
        sidebar_emp_list_btn_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidebar_emp_list_btn_lblMouseClicked(evt);
            }
        });

        sidebar_add_emp_btn_lbl.setBackground(new java.awt.Color(0, 102, 204));
        sidebar_add_emp_btn_lbl.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        sidebar_add_emp_btn_lbl.setForeground(new java.awt.Color(255, 255, 255));
        sidebar_add_emp_btn_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sidebar_add_emp_btn_lbl.setText("Add Employee");
        sidebar_add_emp_btn_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sidebar_add_emp_btn_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidebar_add_emp_btn_lbl.setOpaque(true);
        sidebar_add_emp_btn_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidebar_add_emp_btn_lblMouseClicked(evt);
            }
        });

        sidebar_update_emp_btn_lbl.setBackground(new java.awt.Color(0, 102, 204));
        sidebar_update_emp_btn_lbl.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        sidebar_update_emp_btn_lbl.setForeground(new java.awt.Color(255, 255, 255));
        sidebar_update_emp_btn_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sidebar_update_emp_btn_lbl.setText("View / Update Details");
        sidebar_update_emp_btn_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sidebar_update_emp_btn_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidebar_update_emp_btn_lbl.setOpaque(true);
        sidebar_update_emp_btn_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidebar_update_emp_btn_lblMouseClicked(evt);
            }
        });

        sidebar_delete_emp_btn_lbl.setBackground(new java.awt.Color(0, 102, 204));
        sidebar_delete_emp_btn_lbl.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        sidebar_delete_emp_btn_lbl.setForeground(new java.awt.Color(255, 255, 255));
        sidebar_delete_emp_btn_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sidebar_delete_emp_btn_lbl.setText("Delete Employee");
        sidebar_delete_emp_btn_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sidebar_delete_emp_btn_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidebar_delete_emp_btn_lbl.setOpaque(true);
        sidebar_delete_emp_btn_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidebar_delete_emp_btn_lblMouseClicked(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 2));

        javax.swing.GroupLayout sidebar_menuLayout = new javax.swing.GroupLayout(sidebar_menu);
        sidebar_menu.setLayout(sidebar_menuLayout);
        sidebar_menuLayout.setHorizontalGroup(
            sidebar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar_emp_list_btn_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidebar_add_emp_btn_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidebar_update_emp_btn_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
            .addComponent(sidebar_invoice_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidebar_delete_emp_btn_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        sidebar_menuLayout.setVerticalGroup(
            sidebar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebar_menuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(sidebar_invoice_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sidebar_emp_list_btn_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sidebar_add_emp_btn_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sidebar_update_emp_btn_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sidebar_delete_emp_btn_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar_menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        home_pnl.add(sidebar);
        sidebar.setBounds(0, 0, 260, 587);

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setLayout(new java.awt.CardLayout());

        employee_list_scrl_pane.setBorder(null);

        employee_list_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Type", "Email", "Address", "Date of Joining", "Salary", "Hourly Rate", "Contracted Hours"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        employee_list_scrl_pane.setViewportView(employee_list_tbl);

        content.add(employee_list_scrl_pane, "card7");

        employee_form_pnl.setBackground(new java.awt.Color(255, 255, 255));

        emp_form_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        emp_form_lbl.setText("New Employee");

        emp_id_input.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        emp_id_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        emp_id_lbl.setText("ID");

        emp_address_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        emp_address_lbl.setText("Address");
        emp_address_lbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        emp_address_lbl.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        emp_address_input.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        emp_address_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_address_inputActionPerformed(evt);
            }
        });

        emp_rate_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        emp_rate_lbl.setText("Hourly Rate");

        emp_rate_input.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        emp_hours_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        emp_hours_lbl.setText("Hours");

        emp_hours_input.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        emp_hours_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_hours_inputActionPerformed(evt);
            }
        });

        save_employee_btn_lbl.setBackground(new java.awt.Color(0, 102, 204));
        save_employee_btn_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        save_employee_btn_lbl.setForeground(new java.awt.Color(255, 255, 255));
        save_employee_btn_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save_employee_btn_lbl.setText("Save");
        save_employee_btn_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_employee_btn_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        save_employee_btn_lbl.setOpaque(true);
        save_employee_btn_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save_employee_btn_lblMouseClicked(evt);
            }
        });

        emp_type_full_rdo_btn.setBackground(new java.awt.Color(255, 255, 255));
        emp_type_btn_grp.add(emp_type_full_rdo_btn);
        emp_type_full_rdo_btn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        emp_type_full_rdo_btn.setSelected(true);
        emp_type_full_rdo_btn.setText("Full-time");
        emp_type_full_rdo_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        emp_type_full_rdo_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emp_type_full_rdo_btnMouseClicked(evt);
            }
        });
        emp_type_full_rdo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_type_full_rdo_btnActionPerformed(evt);
            }
        });

        emp_type_part_rdo_btn.setBackground(new java.awt.Color(255, 255, 255));
        emp_type_btn_grp.add(emp_type_part_rdo_btn);
        emp_type_part_rdo_btn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        emp_type_part_rdo_btn.setText("Part-time");
        emp_type_part_rdo_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        emp_type_part_rdo_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emp_type_part_rdo_btnMouseClicked(evt);
            }
        });
        emp_type_part_rdo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_type_part_rdo_btnActionPerformed(evt);
            }
        });

        emp_type_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        emp_type_lbl.setText("Employee Type");

        emp_email_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        emp_email_lbl.setText("Email ID");

        emp_email_input.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        emp_doj_date_input.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        emp_doj_date_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        emp_doj_date_lbl.setText("Date of Joining");

        emp_salary_input.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        emp_salary_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_salary_inputActionPerformed(evt);
            }
        });

        emp_salary_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        emp_salary_lbl.setText("Salary");

        emp_name_input.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        emp_name_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        emp_name_lbl.setText("Name");

        update_employee_btn_lbl.setBackground(new java.awt.Color(0, 102, 204));
        update_employee_btn_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        update_employee_btn_lbl.setForeground(new java.awt.Color(255, 255, 255));
        update_employee_btn_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        update_employee_btn_lbl.setText("Update");
        update_employee_btn_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_employee_btn_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        update_employee_btn_lbl.setOpaque(true);
        update_employee_btn_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_employee_btn_lblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout employee_form_pnlLayout = new javax.swing.GroupLayout(employee_form_pnl);
        employee_form_pnl.setLayout(employee_form_pnlLayout);
        employee_form_pnlLayout.setHorizontalGroup(
            employee_form_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employee_form_pnlLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(employee_form_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employee_form_pnlLayout.createSequentialGroup()
                        .addGroup(employee_form_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emp_hours_lbl)
                            .addComponent(emp_type_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emp_id_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emp_name_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emp_rate_lbl)
                            .addComponent(emp_email_lbl)
                            .addComponent(emp_salary_lbl)
                            .addComponent(emp_address_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 37, Short.MAX_VALUE)
                        .addGroup(employee_form_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, employee_form_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(emp_id_input)
                                .addComponent(emp_address_input, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(employee_form_pnlLayout.createSequentialGroup()
                                    .addComponent(emp_type_full_rdo_btn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(emp_type_part_rdo_btn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emp_doj_date_lbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(emp_doj_date_input, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(emp_name_input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(emp_hours_input, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emp_salary_input, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emp_email_input, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emp_rate_input, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addComponent(emp_form_lbl)
                    .addGroup(employee_form_pnlLayout.createSequentialGroup()
                        .addComponent(save_employee_btn_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(update_employee_btn_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        employee_form_pnlLayout.setVerticalGroup(
            employee_form_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employee_form_pnlLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(emp_form_lbl)
                .addGap(18, 18, 18)
                .addGroup(employee_form_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_id_input, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emp_id_lbl))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(employee_form_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emp_name_lbl))
                .addGap(18, 18, 18)
                .addGroup(employee_form_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employee_form_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emp_type_full_rdo_btn)
                        .addComponent(emp_type_part_rdo_btn)
                        .addComponent(emp_doj_date_lbl)
                        .addComponent(emp_type_lbl))
                    .addComponent(emp_doj_date_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(employee_form_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emp_address_input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emp_address_lbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(employee_form_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_email_input, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emp_email_lbl))
                .addGap(18, 18, 18)
                .addGroup(employee_form_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_rate_input, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emp_rate_lbl))
                .addGap(18, 18, 18)
                .addGroup(employee_form_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_hours_input, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emp_hours_lbl))
                .addGap(18, 18, 18)
                .addGroup(employee_form_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_salary_input, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emp_salary_lbl))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(employee_form_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_employee_btn_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_employee_btn_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        content.add(employee_form_pnl, "card6");

        delete_employee_pnl.setBackground(new java.awt.Color(255, 255, 255));

        delete_employee_lbl.setBackground(new java.awt.Color(255, 255, 255));
        delete_employee_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        delete_employee_lbl.setText("Delete Employee");

        delete_employee_id_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_employee_id_inputActionPerformed(evt);
            }
        });

        delete_employee_id_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        delete_employee_id_lbl.setText("Employee ID");

        delete_employee_btn_lbl.setBackground(new java.awt.Color(0, 102, 204));
        delete_employee_btn_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        delete_employee_btn_lbl.setForeground(new java.awt.Color(255, 255, 255));
        delete_employee_btn_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete_employee_btn_lbl.setText("Delete");
        delete_employee_btn_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_employee_btn_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        delete_employee_btn_lbl.setOpaque(true);
        delete_employee_btn_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_employee_btn_lblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout delete_employee_pnlLayout = new javax.swing.GroupLayout(delete_employee_pnl);
        delete_employee_pnl.setLayout(delete_employee_pnlLayout);
        delete_employee_pnlLayout.setHorizontalGroup(
            delete_employee_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, delete_employee_pnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delete_employee_btn_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278))
            .addGroup(delete_employee_pnlLayout.createSequentialGroup()
                .addGroup(delete_employee_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(delete_employee_pnlLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(delete_employee_id_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete_employee_id_input, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(delete_employee_pnlLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(delete_employee_lbl)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        delete_employee_pnlLayout.setVerticalGroup(
            delete_employee_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delete_employee_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(delete_employee_lbl)
                .addGap(176, 176, 176)
                .addGroup(delete_employee_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete_employee_id_input, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_employee_id_lbl))
                .addGap(34, 34, 34)
                .addComponent(delete_employee_btn_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        content.add(delete_employee_pnl, "card6");

        home_pnl.add(content);
        content.setBounds(260, 60, 785, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, 1042, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delete_employee_btn_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_employee_btn_lblMouseClicked
        int emp_id = Integer.parseInt(delete_employee_id_input.getText());
        DeleteEmployeeController.deleteEmployee(emp_id);
        this.sidebar_emp_list_btn_lblMouseClicked(evt);
    }//GEN-LAST:event_delete_employee_btn_lblMouseClicked

    private void delete_employee_id_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_employee_id_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_employee_id_inputActionPerformed

    private void sidebar_delete_emp_btn_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_delete_emp_btn_lblMouseClicked
        resetLblColor(sidebar_emp_list_btn_lbl);
        resetLblColor(sidebar_add_emp_btn_lbl);
        resetLblColor(sidebar_update_emp_btn_lbl);
        setLblColor(sidebar_delete_emp_btn_lbl);

        employee_form_pnl.setVisible(false);
        employee_list_scrl_pane.setVisible(false);
        delete_employee_pnl.setVisible(true);
    }//GEN-LAST:event_sidebar_delete_emp_btn_lblMouseClicked

    private void sidebar_update_emp_btn_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_update_emp_btn_lblMouseClicked
        resetLblColor(sidebar_emp_list_btn_lbl);
        resetLblColor(sidebar_add_emp_btn_lbl);
        setLblColor(sidebar_update_emp_btn_lbl);
        resetLblColor(sidebar_delete_emp_btn_lbl);

        employee_form_pnl.setVisible(true);
        employee_list_scrl_pane.setVisible(false);
        delete_employee_pnl.setVisible(false);
        
        emp_form_lbl.setText("View / Update Employee");
        emp_doj_date_input.setDate(new Date());
        emp_id_input.setVisible(true);
        emp_id_lbl.setVisible(true);
        update_employee_btn_lbl.setVisible(true);
        save_employee_btn_lbl.setVisible(false);
    }//GEN-LAST:event_sidebar_update_emp_btn_lblMouseClicked

    private void sidebar_add_emp_btn_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_add_emp_btn_lblMouseClicked
        resetLblColor(sidebar_emp_list_btn_lbl);
        setLblColor(sidebar_add_emp_btn_lbl);
        resetLblColor(sidebar_update_emp_btn_lbl);
        resetLblColor(sidebar_delete_emp_btn_lbl);

        employee_form_pnl.setVisible(true);
        employee_list_scrl_pane.setVisible(false);
        delete_employee_pnl.setVisible(false);

        emp_form_lbl.setText("New Employee");
        emp_doj_date_input.setDate(new Date());
        emp_id_input.setVisible(false);
        emp_id_lbl.setVisible(false);
        update_employee_btn_lbl.setVisible(false);
        save_employee_btn_lbl.setVisible(true);
    }//GEN-LAST:event_sidebar_add_emp_btn_lblMouseClicked

    private void sidebar_emp_list_btn_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_emp_list_btn_lblMouseClicked
        setLblColor(sidebar_emp_list_btn_lbl);
        resetLblColor(sidebar_add_emp_btn_lbl);
        resetLblColor(sidebar_update_emp_btn_lbl);
        resetLblColor(sidebar_delete_emp_btn_lbl);

        employee_form_pnl.setVisible(false);
        employee_list_scrl_pane.setVisible(true);
        delete_employee_pnl.setVisible(false);

        DefaultTableModel etm = (DefaultTableModel)employee_list_tbl.getModel();
        ListEmployeesController.listEmployees(etm);
    }//GEN-LAST:event_sidebar_emp_list_btn_lblMouseClicked

    private void headerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseReleased
        setOpacity((float)1.0);
    }//GEN-LAST:event_headerMouseReleased

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        setOpacity((float)0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_headerMouseDragged

    private void exit_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_lblMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exit_lblMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        this.dispose();
        new LoginUI().setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void update_employee_btn_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_employee_btn_lblMouseClicked
        int id = Integer.parseInt(emp_id_input.getText());
        String name = emp_name_input.getText();
        String email = emp_email_input.getText();
        String address = emp_address_input.getText();
        Date doj = emp_doj_date_input.getDate();

        if (emp_type_full_rdo_btn.isSelected()) {
            UpdateEmployeeController.updateEmployee(id, name, "Full-time", email, address, doj);
        } else {
            UpdateEmployeeController.updateEmployee(id, name, "Part-time", email, address, doj);
        }
        this.sidebar_emp_list_btn_lblMouseClicked(evt);
    }//GEN-LAST:event_update_employee_btn_lblMouseClicked

    private void emp_salary_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_salary_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_salary_inputActionPerformed

    private void emp_type_part_rdo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_type_part_rdo_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_type_part_rdo_btnActionPerformed

    private void emp_type_part_rdo_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emp_type_part_rdo_btnMouseClicked
        if(emp_type_part_rdo_btn.isSelected()) {
            emp_rate_lbl.setVisible(true);
            emp_rate_input.setVisible(true);
            emp_hours_lbl.setVisible(true);
            emp_hours_input.setVisible(true);
            emp_salary_lbl.setVisible(false);
            emp_salary_input.setVisible(false);
        } else {
            emp_rate_lbl.setVisible(false);
            emp_rate_input.setVisible(false);
            emp_hours_lbl.setVisible(false);
            emp_hours_input.setVisible(false);
            emp_salary_lbl.setVisible(true);
            emp_salary_input.setVisible(true);
        }
    }//GEN-LAST:event_emp_type_part_rdo_btnMouseClicked

    private void emp_type_full_rdo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_type_full_rdo_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_type_full_rdo_btnActionPerformed

    private void emp_type_full_rdo_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emp_type_full_rdo_btnMouseClicked
        if(emp_type_full_rdo_btn.isSelected()) {
            emp_rate_lbl.setVisible(false);
            emp_rate_input.setVisible(false);
            emp_hours_lbl.setVisible(false);
            emp_hours_input.setVisible(false);
            emp_salary_lbl.setVisible(true);
            emp_salary_input.setVisible(true);
        } else {
            emp_rate_lbl.setVisible(true);
            emp_rate_input.setVisible(true);
            emp_hours_lbl.setVisible(true);
            emp_hours_input.setVisible(true);
            emp_salary_lbl.setVisible(false);
            emp_salary_input.setVisible(false);
        }
    }//GEN-LAST:event_emp_type_full_rdo_btnMouseClicked

    private void save_employee_btn_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_employee_btn_lblMouseClicked
        String name = emp_name_input.getText();
        String email = emp_email_input.getText();
        String address = emp_address_input.getText();
        Date doj = emp_doj_date_input.getDate();

        if(emp_type_full_rdo_btn.isSelected()) {
            AddEmployeeController.addEmployee(name, "Full-time", email, address, doj);
        } else {
            AddEmployeeController.addEmployee(name, "Part-time", email, address, doj);
        }
        this.sidebar_emp_list_btn_lblMouseClicked(evt);
    }//GEN-LAST:event_save_employee_btn_lblMouseClicked

    private void emp_hours_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_hours_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_hours_inputActionPerformed

    private void emp_address_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_address_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_address_inputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ManagerUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JLabel delete_employee_btn_lbl;
    private javax.swing.JTextField delete_employee_id_input;
    private javax.swing.JLabel delete_employee_id_lbl;
    private javax.swing.JLabel delete_employee_lbl;
    private javax.swing.JPanel delete_employee_pnl;
    private javax.swing.JTextField emp_address_input;
    private javax.swing.JLabel emp_address_lbl;
    private com.toedter.calendar.JDateChooser emp_doj_date_input;
    private javax.swing.JLabel emp_doj_date_lbl;
    private javax.swing.JTextField emp_email_input;
    private javax.swing.JLabel emp_email_lbl;
    private javax.swing.JLabel emp_form_lbl;
    private javax.swing.JTextField emp_hours_input;
    private javax.swing.JLabel emp_hours_lbl;
    private javax.swing.JTextField emp_id_input;
    private javax.swing.JLabel emp_id_lbl;
    private javax.swing.JTextField emp_name_input;
    private javax.swing.JLabel emp_name_lbl;
    private javax.swing.JTextField emp_rate_input;
    private javax.swing.JLabel emp_rate_lbl;
    private javax.swing.JTextField emp_salary_input;
    private javax.swing.JLabel emp_salary_lbl;
    private javax.swing.ButtonGroup emp_type_btn_grp;
    private javax.swing.JRadioButton emp_type_full_rdo_btn;
    private javax.swing.JLabel emp_type_lbl;
    private javax.swing.JRadioButton emp_type_part_rdo_btn;
    private javax.swing.JPanel employee_form_pnl;
    private javax.swing.JScrollPane employee_list_scrl_pane;
    private javax.swing.JTable employee_list_tbl;
    private javax.swing.JLabel exit_lbl;
    private javax.swing.JPanel exit_pnl;
    private javax.swing.JPanel header;
    private javax.swing.JPanel home_pnl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel save_employee_btn_lbl;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel sidebar_add_emp_btn_lbl;
    private javax.swing.JLabel sidebar_delete_emp_btn_lbl;
    private javax.swing.JLabel sidebar_emp_list_btn_lbl;
    private javax.swing.JLabel sidebar_invoice_lbl;
    private javax.swing.JPanel sidebar_menu;
    private javax.swing.JLabel sidebar_update_emp_btn_lbl;
    private javax.swing.JLabel update_employee_btn_lbl;
    private javax.swing.JLabel user_login_heading_lbl;
    // End of variables declaration//GEN-END:variables
}
